### ISSUE TITLE
dev_landmarks branch needs to be turned inactive or deleted

### ISSUE THREAD

**Issue by ralfbanisch** [DiffusionMapsAcademics/pyDiffMap#15]
The dev_landmarks branch is now superseeded by dev_landmarks_v2. We should turn the old branch inactive or delete it.

Sorry guys, I'm opening the issue because I didn't feel comfortable doing something like deleting without asking for consent.

**Comment by ehthiede** [comment]
Oh, go for it!

-Erik

**Comment by ralfbanisch** [comment]
ok, done. I'll close this then.
