### ISSUE TITLE
Compatibility with scipy 1.0.0

### ISSUE THREAD

**Issue by ppxasjsm** [DiffusionMapsAcademics/pyDiffMap#17]
Between scipy 0.19.0 and below and 1.0.0 `logsumexp` has been moved from `scipy.misc` to `scipy.special`.

This is currently not accounted for.

**Comment by ehthiede** [comment]
Hi Toni: Thanks for raising the issue.   Just to make sure I understand, the issue here is that the scipy.special / scipy.misc difference breaks backwards compatibility for scipy versions earlier than 1.0.0?

**Comment by ppxasjsm** [comment]
Yep. That is exactly it!

**Comment by ehthiede** [comment]
Great.  I added a tweak in the branch dev_old_scipy.  Could you see if that fixes your problem?

**Comment by ppxasjsm** [comment]
Fixed things thanks! (And sorry for the slow reply I was distracted by other things. )

**Comment by ehthiede** [comment]
Quick follow up: as of today these changes have been pushed to master.
