### ISSUE TITLE
Documentation Needs Theory Section

### ISSUE THREAD

**Issue by ehthiede** [DiffusionMapsAcademics/pyDiffMap#2]
The documentation could use a theory section introducing what diffusion maps are.

**Comment by ralfbanisch** [comment]
I'll give this a go.

**Comment by ralfbanisch** [comment]
There is now a theory section on /dev as per b10431cc22b4e7bbe985a6ef5d8c67b9c261ed5d

**Comment by ralfbanisch** [comment]
Closing this one too :)
