### ISSUE TITLE
Error in Theory

### ISSUE THREAD

**Issue by Javihaus** [DiffusionMapsAcademics/pyDiffMap#23]
I think you have a small error under Theory:
"where Δ is the Laplace Beltrami operator, ∇ is the gradient" and should be the opposite: ∇ the Laplace operator and Δ the gradient.

**Comment by ehthiede** [comment]
Actually, I think it's correct as written: see the excerpt from the Wikipedia page on the Laplace-Beltrami operator.

![image](https://user-images.githubusercontent.com/15326830/192585925-26987694-e97d-47b8-9908-b64c75aef397.png)
