### ISSUE TITLE
Documentation Needs Demo Sections

### ISSUE THREAD

**Issue by ehthiede** [DiffusionMapsAcademics/pyDiffMap#3]
We need demos in the documentation to guide people through using the code.  For instance, it would be great to put Ralf's Swiss Roll in as an example.

**Comment by ralfbanisch** [comment]
working on it, a minimal implementation is now in \dev.

**Comment by ehthiede** [comment]
Thanks!  If you feel comfortable taking this on in a more official way, feel free to assign the issue to yourself using the option on the right.

**Comment by ralfbanisch** [comment]
I'm closing this.
