### ISSUE TITLE
Doc Strings Need Example Usage

### ISSUE THREAD

**Issue by ehthiede** [DiffusionMapsAcademics/pyDiffMap#4]
The current doc strings have _Parameters_ and _Returns_ sections.  However, they **don't** have an _Examples_ section.  We should have them.

Currently, the docstrings obey the numpy convention, which you can read about [here](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt).  There is also an example of a docstring obeying this format [here](https://github.com/numpy/numpy/blob/master/doc/example.py).

**Comment by ralfbanisch** [comment]
I'm not sure how to best do this. Our functions are quite high level - it's not like we simply add two numbers or something, we perform a rather sophisticated analysis on datasets that often have to be generated or pulled first. In scikit-learn, high level classification or regression functions don't have examples in the API. Rather, the API simply links to example notebooks. Should we do the same?

Alternatively, where should examples go? In the doc string of the class? Or in the doc string of each routine of said class? Very often however, the routines don't really make sense on their own. For example, fit(..) doesn't make sense without calling __init__(...) first.

**Comment by ehthiede** [comment]
Good point... maybe the way to go is to just link the example notebooks, like sckit-learn.

**Comment by ehthiede** [comment]
I closed this because in retrospect, I think Ralf is right and this isn't really necessary.
